
version: '3.8'
services:

#Nginx Service
  webserver:
    image: nginx:alpine
    container_name: dms_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/error.log:/var/log/nginx/error.log
      - ./docker/nginx/access.log:/var/log/nginx/access.log
    networks:
      - dms_networks
    depends_on:
      - mysql
#PHP Service
  app:
    image: php_8.2_image
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dms_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "8001:9000"
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dms_networks
    depends_on:
      - mysql
#MySql
  mysql:
    container_name: dms_mysql
    image:    'mysql:8.0'
    restart:  always
    ports:
      - "8003:3306"
    volumes:
      - rundbdata:/var/run/mysqld
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER:     '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - dms_networks 
networks:
  dms_networks:
    driver: bridge
volumes:
  rundbdata: