version: "3.8"

services:
  front-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www
      - node_modules:/var/www/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

volumes:
  node_modules:
