version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ./node_modules:/var/www/node_modules
    # environment:
    #   NODE_ENV: production
    # Uncomment if your app needs to run on a specific port
    # ports:
    #   - "3000:3000"
