<?php

return [
  "identity_photo"           => "identityPhoto",
  "right_thumb_print"        => "rightThumbPrint",
  "right_index_print"        => "rightIndexPrint",
  "right_middle_print"       => "rightMiddlePrint",
  "right_ring_print"         => "rightRingPrint",
  "right_pinky_print"        => "rightPinkyPrint",
  "left_thumb_print"         => "leftThumbPrint",
  "left_index_print"         => "leftIndexPrint",
  "left_middle_print"        => "leftMiddlePrint",
  "left_ring_print"          => "leftRingPrint",
  "left_pinky_print"         => "leftPinkyPrint",
  "front_body_photo"         => "frontBodyPhoto",
  "right_profile_photo"      => "rightProfilePhoto",
  "left_profile_photo"       => "leftProfilePhoto",
  "four_left_fingers_print"  => "fourLeftFingersPrint",
  "left_thumb_print01"       => "leftThumbPrint01",
  "right_thumb_print01"      => "rightThumbPrint01",
  "four_right_fingers_print" => "fourRightFingersPrint",
  "left_palm_print"          => "leftPalmPrint",
  "right_palm_print"         => "rightPalmPrint",
  "special_mark1"            => "specialMark1",
  "special_mark2"            => "specialMark2",
  "special_mark3"            => "specialMark3",
  "form_template"            => "formTemplate",
  "form_template_1"            => "formTemplate1",
  "form_template_2"            => "formTemplate2"
];